# Generated by Django 2.2.5 on 2019-09-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewedrafts',
            name='price',
        ),
    ]
