# Generated by Django 2.2.5 on 2019-09-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_viewedrafts_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='viewedRafts',
        ),
    ]
