# Generated by Django 2.2.5 on 2019-09-06 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_viewedrafts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewedRafts',
        ),
    ]
