# Generated by Django 2.2.5 on 2019-09-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0005_delete_viewedrafts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedRafts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('num_reviews', models.IntegerField()),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=15)),
                ('zip_code', models.IntegerField()),
                ('time_viewed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
